name: 'intersection_observer'
version: 1.0.0
description: Intersection Observer API for Dart
author: Rob Becker <robrbecker@gmail.com>
homepage: https://github.com/robrbecker/intersection_observer

environment:
  sdk: '>=1.22.1 <2.0.0'

dev_dependencies:
  browser: ^0.10.0
  js: ^0.6.1

transformers:
- $dart2js:
    sourceMaps: true
